#!/bin/bash
# Package the Swift Package executable into a real macOS .app bundle.
#
# Why this exists: `swift build` emits a unix-style binary, but the OS needs
# a proper .app structure (Contents/MacOS, Contents/Info.plist, ...) to
# register CFBundleDocumentTypes — i.e., to make photo-viewer appear in
# Finder's "Open With…" menu for image files.
#
# Output: ./build/Latent.app — drop into /Applications or run in place.
#
# When the project migrates to an Xcode workspace this script gets retired:
# Xcode produces the .app via xcodebuild and adds code signing + the QL
# extension target.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

APP_NAME="Latent"
APP_DIR="build/${APP_NAME}.app"
BINARY_NAME="Latent"
INFO_PLIST="Resources/AppBundle/Info.plist"

# 1. Build release. `--product` (not `--target`) is what actually links the
#    executable; `--target` would only compile the module sources.
echo "==> swift build -c release --product $APP_NAME"
swift build -c release --product "$APP_NAME"

BINARY_PATH="$(swift build -c release --show-bin-path)/$BINARY_NAME"
if [[ ! -x "$BINARY_PATH" ]]; then
    echo "error: built binary not found at $BINARY_PATH" >&2
    exit 1
fi

# 2. Build the bundle scaffold.
echo "==> assembling $APP_DIR"
rm -rf "$APP_DIR"
mkdir -p "$APP_DIR/Contents/MacOS" "$APP_DIR/Contents/Resources"
cp "$BINARY_PATH" "$APP_DIR/Contents/MacOS/$BINARY_NAME"
chmod +x "$APP_DIR/Contents/MacOS/$BINARY_NAME"
cp "$INFO_PLIST" "$APP_DIR/Contents/Info.plist"

# 3. Copy the app icon. Generated by scripts/generate_icon.swift, which
#    writes Latent.icns alongside the iconset folder. CFBundleIconFile in
#    Info.plist names this file (sans extension).
ICON="Resources/AppBundle/Latent.icns"
if [[ -f "$ICON" ]]; then
    cp "$ICON" "$APP_DIR/Contents/Resources/Latent.icns"
else
    echo "warning: Latent.icns missing — run 'swift scripts/generate_icon.swift'" >&2
fi

# 4. Bundle any locally converted AI assets. These directories are mostly
# gitignored, so a build without local models stays small; a build with them
# remains functional after the app moves away from this source checkout.
for resource_dir in Models Tokenizer; do
    if [[ -d "Resources/$resource_dir" ]]; then
        cp -R "Resources/$resource_dir" "$APP_DIR/Contents/Resources/$resource_dir"
    fi
done

# 5. Seal the bundle. SwiftPM ad-hoc signs the executable at link time, but
#    nothing signs the *bundle*, so there is no _CodeSignature/CodeResources
#    and `codesign --verify` fails with "code has no resources but signature
#    indicates they must be present". On Apple silicon that can surface to a
#    user as "the application is damaged". Must run last — after the Info.plist,
#    icon and any model assets are in place, or the seal won't match.
#    LATENT_SIGNING_IDENTITY can name a Developer ID for a distribution build;
#    the default "-" is ad-hoc, which is what a local build wants.
SIGNING_IDENTITY="${LATENT_SIGNING_IDENTITY:--}"
codesign --force --deep --sign "$SIGNING_IDENTITY" --timestamp=none "$APP_DIR"
codesign --verify --deep --strict --verbose=2 "$APP_DIR"

# 6. Touch the bundle so Launch Services re-reads it. Without this, Finder
#    sometimes serves a stale Info.plist from its cache and won't show the
#    app in "Open With…".
touch "$APP_DIR"

echo
echo "Built $APP_DIR"
echo "  - To run:        open $APP_DIR"
echo "  - To install:    cp -r $APP_DIR /Applications/"
echo "  - Register types: /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -f $APP_DIR"
