#!/bin/bash
# Package the Swift Package executable into a real macOS .app bundle.
#
# Why this exists: `swift build` emits a unix-style binary, but the OS needs
# a proper .app structure (Contents/MacOS, Contents/Info.plist, ...) to
# register CFBundleDocumentTypes — i.e., to make photo-viewer appear in
# Finder's "Open With…" menu for image files.
#
# Output: ./build/Latent.app — drop into /Applications or run in place.
#
# When the project migrates to an Xcode workspace this script gets retired:
# Xcode produces the .app via xcodebuild and adds code signing + the QL
# extension target.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

APP_NAME="Latent"
APP_DIR="build/${APP_NAME}.app"
BINARY_NAME="Latent"
INFO_PLIST="Resources/AppBundle/Info.plist"
PLIST_BUDDY="/usr/libexec/PlistBuddy"

# 1. Build release. `--product` (not `--target`) is what actually links the
#    executable; `--target` would only compile the module sources.
echo "==> swift build -c release --product $APP_NAME"
swift build -c release --product "$APP_NAME"

BUILD_BIN_DIR="$(swift build -c release --show-bin-path)"
BINARY_PATH="$BUILD_BIN_DIR/$BINARY_NAME"
if [[ ! -x "$BINARY_PATH" ]]; then
    echo "error: built binary not found at $BINARY_PATH" >&2
    exit 1
fi

# 2. Build the bundle scaffold.
echo "==> assembling $APP_DIR"
rm -rf "$APP_DIR"
mkdir -p "$APP_DIR/Contents/MacOS" "$APP_DIR/Contents/Resources" "$APP_DIR/Contents/Frameworks"
cp "$BINARY_PATH" "$APP_DIR/Contents/MacOS/$BINARY_NAME"
chmod +x "$APP_DIR/Contents/MacOS/$BINARY_NAME"
cp "$INFO_PLIST" "$APP_DIR/Contents/Info.plist"

# Release automation can inject version/build/update key material without
# editing the source plist. Local builds keep the checked-in defaults.
if [[ -n "${LATENT_VERSION:-}" ]]; then
    "$PLIST_BUDDY" -c "Set :CFBundleShortVersionString $LATENT_VERSION" "$APP_DIR/Contents/Info.plist"
fi
if [[ -n "${LATENT_BUILD_NUMBER:-}" ]]; then
    "$PLIST_BUDDY" -c "Set :CFBundleVersion $LATENT_BUILD_NUMBER" "$APP_DIR/Contents/Info.plist"
fi
if [[ -n "${SPARKLE_PUBLIC_ED_KEY:-}" ]]; then
    "$PLIST_BUDDY" -c "Set :SUPublicEDKey $SPARKLE_PUBLIC_ED_KEY" "$APP_DIR/Contents/Info.plist"
fi

# SwiftPM links Sparkle through @rpath. A manually assembled .app must embed
# the framework and carry the standard app Frameworks rpath.
SPARKLE_FRAMEWORK="$BUILD_BIN_DIR/Sparkle.framework"
if [[ -d "$SPARKLE_FRAMEWORK" ]]; then
    cp -R "$SPARKLE_FRAMEWORK" "$APP_DIR/Contents/Frameworks/"
    if ! otool -l "$APP_DIR/Contents/MacOS/$BINARY_NAME" | grep -q '@executable_path/../Frameworks'; then
        install_name_tool -add_rpath "@executable_path/../Frameworks" "$APP_DIR/Contents/MacOS/$BINARY_NAME"
    fi
else
    echo "warning: Sparkle.framework missing at $SPARKLE_FRAMEWORK" >&2
fi

# 3. Copy the app icon. Generated by scripts/generate_icon.swift, which
#    writes Latent.icns alongside the iconset folder. CFBundleIconFile in
#    Info.plist names this file (sans extension).
ICON="Resources/AppBundle/Latent.icns"
if [[ -f "$ICON" ]]; then
    cp "$ICON" "$APP_DIR/Contents/Resources/Latent.icns"
else
    echo "warning: Latent.icns missing — run 'swift scripts/generate_icon.swift'" >&2
fi

# 4. Sign the bundle. Local builds use ad-hoc signing so the embedded Sparkle
#    framework and the main executable agree. Release workflows can pass a
#    Developer ID Application identity via CODE_SIGN_IDENTITY. Do not use
#    --deep for Developer ID distribution; sign nested Sparkle code explicitly.
if [[ -n "${CODE_SIGN_IDENTITY:-}" ]]; then
    SPARKLE_IN_APP="$APP_DIR/Contents/Frameworks/Sparkle.framework"
    if [[ -d "$SPARKLE_IN_APP" ]]; then
        codesign --force --sign "$CODE_SIGN_IDENTITY" --options runtime \
            "$SPARKLE_IN_APP/Versions/B/XPCServices/Installer.xpc"
        codesign --force --sign "$CODE_SIGN_IDENTITY" --options runtime \
            --preserve-metadata=entitlements \
            "$SPARKLE_IN_APP/Versions/B/XPCServices/Downloader.xpc"
        codesign --force --sign "$CODE_SIGN_IDENTITY" --options runtime \
            "$SPARKLE_IN_APP/Versions/B/Autoupdate"
        codesign --force --sign "$CODE_SIGN_IDENTITY" --options runtime \
            "$SPARKLE_IN_APP/Versions/B/Updater.app"
        codesign --force --sign "$CODE_SIGN_IDENTITY" --options runtime \
            "$SPARKLE_IN_APP"
    fi
    codesign --force --sign "$CODE_SIGN_IDENTITY" --options runtime "$APP_DIR"
else
    codesign --force --deep --sign - "$APP_DIR" >/dev/null 2>&1 || true
fi

# 5. Touch the bundle so Launch Services re-reads it. Without this, Finder
#    sometimes serves a stale Info.plist from its cache and won't show the
#    app in "Open With…".
touch "$APP_DIR"

echo
echo "Built $APP_DIR"
echo "  - To run:        open $APP_DIR"
echo "  - To install:    cp -r $APP_DIR /Applications/"
echo "  - Register types: /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -f $APP_DIR"
